development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://:9BZA9Iko8512HGJkkK530PymTwNAOF08@redis-15803.c8.us-east-1-3.ec2.cloud.redislabs.com:15803
  channel_prefix: dontpad_production
